# Generated by Django 5.0.7 on 2024-10-02 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AESP_odonto_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CONDICAO', models.CharField(default='1', max_length=1)),
                ('NRO_CONTRATO', models.CharField(max_length=100)),
                ('DATA_MOVIMENTO', models.DateTimeField()),
                ('DATA_INICIO_UTILIZACAO', models.DateTimeField()),
                ('TIPO', models.CharField(default='TI', max_length=2)),
                ('NOME', models.CharField(max_length=255)),
                ('NOME_MAE', models.CharField(max_length=255)),
                ('DATA_NASCIMENTO', models.DateField()),
                ('TIPO_LOGRADOURO', models.IntegerField(choices=[(1, 'RUA'), (2, 'AVENIDA'), (3, 'ALAMEDA'), (4, 'TRAVESSA'), (5, 'ACESSO'), (6, 'BALNEÁRIO'), (7, 'ESTRADA'), (8, 'FAZENDA'), (9, 'SÍTIO'), (10, 'CHÁCARA'), (11, 'OUTRO'), (12, 'VIA'), (13, 'PRAÇA'), (14, 'BOULEVARD'), (15, 'RODOVIA'), (16, 'QUADRA'), (17, 'CONDOMINIO')])),
                ('NOME_LOGRADOURO', models.CharField(max_length=255)),
                ('NUMERO', models.CharField(max_length=10)),
                ('BAIRRO', models.CharField(max_length=100)),
                ('COMPLEMENTO', models.CharField(blank=True, max_length=100, null=True)),
                ('CIDADE', models.CharField(max_length=100)),
                ('ESTADO', models.CharField(max_length=2)),
                ('CEP', models.CharField(max_length=9)),
                ('RG', models.CharField(max_length=20)),
                ('UF_RG', models.CharField(max_length=2)),
                ('CPF', models.CharField(max_length=11)),
                ('SEXO', models.IntegerField(choices=[(1, 'Feminino'), (2, 'Masculino')])),
                ('ESTADO_CIVIL', models.IntegerField(choices=[(1, 'Amasiado(a)'), (2, 'Casado(a)'), (3, 'Divorciado(a)'), (5, 'Separado(a)'), (6, 'Solteiro(a)'), (7, 'Viúvo(a)')])),
                ('EMAIL', models.EmailField(max_length=254)),
                ('DDD', models.CharField(max_length=2)),
                ('FONE', models.CharField(max_length=10)),
                ('CODIGOPLANODATASYS', models.CharField(default=196702, max_length=20)),
                ('STATUS', models.CharField(default='Ativo', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIPO', models.CharField(default='DE', max_length=2)),
                ('NOME', models.CharField(max_length=255)),
                ('NOME_MAE', models.CharField(max_length=255)),
                ('DATA_NASCIMENTO', models.DateField()),
                ('CPF_DEPENDENTE', models.CharField(max_length=11)),
                ('SEXO', models.IntegerField(choices=[(1, 'Feminino'), (2, 'Masculino')])),
                ('ESTADO_CIVIL', models.IntegerField(choices=[(1, 'Amasiado(a)'), (2, 'Casado(a)'), (3, 'Divorciado(a)'), (5, 'Separado(a)'), (6, 'Solteiro(a)'), (7, 'Viúvo(a)')])),
                ('GRAU_DEPENDENCIA', models.CharField(choices=[('2E', 'Esposa ou companheira'), ('2C', 'Esposo ou companheiro'), ('3M', 'Filhos'), ('3F', 'Filhas'), ('4M', 'Agregado masculino'), ('4F', 'Agregado feminino'), ('5P', 'Pai'), ('5M', 'Mãe')], max_length=10)),
                ('RG', models.CharField(blank=True, max_length=20, null=True)),
                ('ORGAO_EMISSOR', models.CharField(blank=True, max_length=100, null=True)),
                ('STATUS', models.CharField(default='Ativo', max_length=20, null=True)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='empresas_AESP_odonto.aesp_odonto_empresa')),
            ],
        ),
    ]
