# Generated by Django 5.0.7 on 2024-08-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AESP_odonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CONDICAO', models.CharField(default='1', max_length=1)),
                ('NRO_CONTRATO', models.CharField(max_length=100)),
                ('DATA_MOVIMENTO', models.DateTimeField()),
                ('DATA_INICIO_UTILIZACAO', models.DateField()),
                ('TIPO', models.CharField(choices=[('TI', 'Titular'), ('DE', 'Dependente')], max_length=2)),
                ('GRAU_DEPENDENCIA', models.CharField(choices=[('1M', 'Titular do sexo masculino'), ('1F', 'Titular do sexo feminino'), ('2E', 'Esposa ou companheira'), ('2C', 'Esposo ou companheiro'), ('3M', 'Filhos'), ('3F', 'Filhas'), ('4M', 'Agregado masculino'), ('4F', 'Agregado feminino'), ('5P', 'Pai'), ('5M', 'Mãe')], max_length=10)),
                ('NOME', models.CharField(max_length=255)),
                ('NOME_MAE', models.CharField(max_length=255)),
                ('DATA_NASCIMENTO', models.DateField()),
                ('TIPO_LOGRADOURO', models.IntegerField(choices=[(1, 'RUA'), (2, 'AVENIDA'), (3, 'ALAMEDA'), (4, 'TRAVESSA'), (5, 'ACESSO'), (6, 'BALNEÁRIO'), (7, 'ESTRADA'), (8, 'FAZENDA'), (9, 'SÍTIO'), (10, 'CHÁCARA'), (11, 'OUTRO'), (12, 'VIA'), (13, 'PRAÇA'), (14, 'BOULEVARD'), (15, 'RODOVIA'), (16, 'QUADRA'), (17, 'CONDOMINIO')])),
                ('NOME_LOGRADOURO', models.CharField(max_length=255)),
                ('NUMERO', models.CharField(max_length=10)),
                ('BAIRRO', models.CharField(max_length=100)),
                ('COMPLEMENTO', models.CharField(max_length=100)),
                ('CIDADE', models.CharField(max_length=100)),
                ('ESTADO', models.CharField(max_length=2)),
                ('CEP', models.CharField(max_length=8)),
                ('RG', models.CharField(max_length=20)),
                ('UF_RG', models.CharField(max_length=2)),
                ('CPF_TITULAR', models.CharField(max_length=11)),
                ('CPF', models.CharField(max_length=11)),
                ('PIS', models.CharField(max_length=50)),
                ('SEXO', models.IntegerField(choices=[(1, 'Feminino'), (2, 'Masculino')])),
                ('ESTADO_CIVIL', models.IntegerField(choices=[(1, 'Amasiado(a)'), (2, 'Casado(a)'), (3, 'Divorciado(a)'), (5, 'Separado(a)'), (6, 'Solteiro(a)'), (7, 'Viúvo(a)')])),
                ('DDD', models.CharField(max_length=2)),
                ('FONE', models.CharField(max_length=10)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('CODIGOPLANODATASYS', models.CharField(default=196702, max_length=20)),
            ],
        ),
    ]
