# Generated by Django 5.0.7 on 2024-08-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESP_odonto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aesp_odonto',
            name='GRAU_DEPENDENCIA',
            field=models.CharField(choices=[('1M', 'Titular do sexo masculino'), ('1F', 'Titular do sexo feminino'), ('2E', 'Esposa ou companheira'), ('2C', 'Esposo ou companheiro'), ('3M', 'Filhos'), ('3F', 'Filhas'), ('4M', 'Agregado masculino'), ('4F', 'Agregado feminino'), ('5P', 'Pai'), ('5M', 'Mãe')], max_length=10),
        ),
    ]
