# Generated by Django 5.1.1 on 2025-06-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESP_odonto', '0002_aesp_odonto_pastor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aesp_odonto',
            name='CODIGOPLANODATASYS',
            field=models.CharField(choices=[('ROL_ANS', 'ROL ANS'), ('ROL_MAIS', 'ROL +')], max_length=20),
        ),
    ]
